### ISSUE TITLE
Unable to install most dependencies

### ISSUE THREAD

**Issue by Parnswir** [bottlesdevs/dependencies#166]
I'm running bottles on a Steam Deck, but I can't manage to install most dependencies and programs due to errors like the one below. Is there something wrong with my environment?

```
d3dx9.tar.xz (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (19.7 MB/19.7 MB - 4.0 MB)

patool: Extracting /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz ...
patool: running /usr/bin/tar --extract --use-compress-program xz --file /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz --directory /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar
patool: ... /home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar.xz extracted to `/home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar'.
Something wrong happened during extraction.
file `/home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found
Traceback (most recent call last):
          File "/app/share/bottles/bottles/backend/managers/dependency.py", line 514, in __step_archive_extract
            patoolib.extract_archive(tar_path, outdir=archive_path)
          File "/app/lib/python3.10/site-packages/patoolib/__init__.py", line 681, in extract_archive
            util.check_existing_filename(archive)
          File "/app/lib/python3.10/site-packages/patoolib/util.py", line 398, in check_existing_filename
            raise PatoolError("file `%s' was not found" % filename)
        patoolib.util.PatoolError: file `/home/deck/.var/app/com.usebottles.bottles/data/bottles/temp/d3dx9.tar/d3dx9.tar' was not found
```

```
Official Package: true
Version: '51.0'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve36-1-neptune
Disk:
    Total: 7769219072
    Free: 7769071616
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 11.2GiB
Bottles_envs: null
```

**Comment by Kinsteen** [comment]
There is an update that should fix this, come back and send logs if it doesn't!

**Comment by Parnswir** [comment]
indeed, it seems to work with the latest update. Many thanks for the quick response!
